"""Output writers for JSON, CSV, text, and HTML reports."""

from __future__ import annotations

import csv
import html
import json
from dataclasses import asdict
from pathlib import Path
from typing import Iterable, List

from . import __version__
from .models import Finding, Profile
from .scoring import summarize


def write_json(findings: Iterable[Finding], out_dir: Path) -> None:
    (out_dir / "findings.json").write_text(
        json.dumps(
            [asdict(finding) for finding in findings],
            indent=2,
        ),
        encoding="utf-8",
    )


def write_csv(findings: Iterable[Finding], out_dir: Path) -> None:
    fieldnames = [
        "check_id",
        "title",
        "status",
        "severity",
        "category",
        "evidence",
        "rationale",
        "recommendation",
    ]

    with (out_dir / "findings.csv").open(
        "w",
        newline="",
        encoding="utf-8",
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for finding in findings:
            writer.writerow(asdict(finding))


def _summary_lines(
    findings: List[Finding],
    profile: Profile,
) -> List[str]:
    summary = summarize(findings, profile)
    return [
        f"Security Baseline Compliance Auditor v{__version__}",
        f"Profile: {profile.name} ({profile.profile_id} v{profile.version})",
        f"Baseline checks run: {summary['total_checks']}",
        f"Passed: {summary['passed']}",
        f"Failed: {summary['failed']}",
        f"Compliance score: {summary['compliance_score']}%",
        f"Critical findings: {summary['critical']}",
        f"High findings: {summary['high']}",
        f"Medium findings: {summary['medium']}",
        f"Low findings: {summary['low']}",
    ]


def write_summary(
    findings: List[Finding],
    profile: Profile,
    out_dir: Path,
) -> None:
    (out_dir / "summary.txt").write_text(
        "\n".join(_summary_lines(findings, profile)) + "\n",
        encoding="utf-8",
    )


def write_html(
    findings: List[Finding],
    profile: Profile,
    out_dir: Path,
) -> None:
    summary = summarize(findings, profile)
    rows = []

    for finding in findings:
        rows.append(
            "<tr>"
            f"<td>{html.escape(finding.check_id)}</td>"
            f"<td>{html.escape(finding.status)}</td>"
            f"<td>{html.escape(finding.severity)}</td>"
            f"<td>{html.escape(finding.category)}</td>"
            f"<td>{html.escape(finding.title)}</td>"
            f"<td>{html.escape(finding.evidence)}</td>"
            f"<td>{html.escape(finding.rationale)}</td>"
            f"<td>{html.escape(finding.recommendation)}</td>"
            "</tr>"
        )

    document = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Security Baseline Compliance Report</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      margin: 2rem;
      line-height: 1.4;
    }}
    table {{
      border-collapse: collapse;
      width: 100%;
      font-size: 0.9rem;
    }}
    th, td {{
      border: 1px solid #ccc;
      padding: 6px;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      background: #f2f2f2;
    }}
    .score {{
      font-size: 1.4rem;
      font-weight: bold;
    }}
    .meta {{
      color: #555;
      font-size: 0.9rem;
    }}
  </style>
</head>
<body>
  <h1>Security Baseline Compliance Report</h1>
  <p class="meta">Generated by Security Baseline Compliance Auditor v{__version__}</p>
  <p class="meta">Profile: {html.escape(profile.name)} ({html.escape(profile.profile_id)} v{html.escape(profile.version)})</p>
  <p class="score">Compliance Score: {summary['compliance_score']}%</p>
  <ul>
    <li>Baseline checks run: {summary['total_checks']}</li>
    <li>Passed: {summary['passed']}</li>
    <li>Failed: {summary['failed']}</li>
    <li>Critical findings: {summary['critical']}</li>
    <li>High findings: {summary['high']}</li>
    <li>Medium findings: {summary['medium']}</li>
    <li>Low findings: {summary['low']}</li>
  </ul>
  <table>
    <tr>
      <th>Check ID</th>
      <th>Status</th>
      <th>Severity</th>
      <th>Category</th>
      <th>Title</th>
      <th>Evidence</th>
      <th>Rationale</th>
      <th>Recommendation</th>
    </tr>
    {''.join(rows)}
  </table>
</body>
</html>
"""
    (out_dir / "report.html").write_text(
        document,
        encoding="utf-8",
    )


def write_all(
    findings: List[Finding],
    profile: Profile,
    out_dir: Path,
) -> None:
    write_json(findings, out_dir)
    write_csv(findings, out_dir)
    write_summary(findings, profile, out_dir)
    write_html(findings, profile, out_dir)
